# Generated by Django 4.2.1 on 2024-10-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentComment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.comment'),
        ),
    ]
